export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const DECREASE_CART_ITEM_QTY = "DECREASE_CART_ITEM_QTY";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_FROM_DB = "UPDATE_CART_FROM_DB";
export const FETCH_CART_FROM_DB = "FETCH_CART_FROM_DB";
export const MOVE_CART_TO_HISTORY = "MOVE_CART_TO_HISTORY";
