export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const START_EMAIL_SIGN_IN = "START_EMAIL_SIGN_IN";
export const START_GOOGLE_SIGN_IN = "START_GOOGLE_SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
