export const CHECK_USER_SESSION = "CHECK_USER_SESSION";
export const START_EMAIL_SIGN_IN = "START_EMAIL_SIGN_IN";
export const START_GOOGLE_SIGN_IN = "START_GOOGLE_SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const SIGN_OUT_START = "SIGN_OUT_START";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";

export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
